{
 "title": "Garmin Activity Detail",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "ActivityGPS",
    "label": "Activity with GPS",
    "query": {
     "query": "SHOW TAG VALUES FROM \"ActivityGPS\" WITH KEY = \"ActivitySelector\" WHERE $timeFilter"
    }
   },
   {
    "name": "TimeZone",
    "label": "Local Time Zone",
    "query": "Europe/London, Europe/Paris, Europe/Berlin, Europe/Madrid, Europe/Rome, Europe/Amsterdam, Europe/Brussels, Europe/Zurich, Europe/Stockholm, Europe/Warsaw, Europe/Budapest, Europe/Istanbul, Europe/Athens, Europe/Moscow, America/New_York, America/Chicago, America/Denver, America/Los_Angeles, America/Toronto, America/Vancouver, America/Mexico_City, America/Sao_Paulo, America/Buenos_Aires, America/Lima, America/Bogota, Africa/Johannesburg, Africa/Cairo, Africa/Nairobi, Africa/Lagos, Asia/Tokyo, Asia/Seoul, Asia/Shanghai, Asia/Singapore, Asia/Kolkata, Asia/Bangkok, Asia/Dubai, Asia/Hong_Kong, Asia/Kuala_Lumpur, Asia/Jakarta, Asia/Manila, Asia/Taipei, Asia/Karachi, Asia/Colombo, Asia/Ho_Chi_Minh, Australia/Sydney, Australia/Melbourne, Australia/Brisbane, Australia/Perth, Pacific/Auckland, Pacific/Honolulu"
   }
  ]
 },
 "panels": [
  { "title": "Select Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Recent Activity",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Activity Type",
     "measurement": "ActivitySummary",
     "query": "SELECT \"duration\" FROM \"Activity Records\" WHERE (\"ActivityName\" = 'Walk') AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "activityType" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "activityType::field", "operator": "!=", "value": "No Activity" }
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Duration",
     "measurement": "ActivitySummary",
     "query": "SELECT \"duration\" FROM \"Activity Records\" WHERE (\"ActivityName\" = 'Walk') AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "elapsedDuration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "activityType::field", "operator": "!=", "value": "No Activity" }
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Max HR",
     "measurement": "ActivitySummary",
     "query": "SELECT \"duration\" FROM \"Activity Records\" WHERE (\"ActivityName\" = 'Walk') AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "maxHR" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "activityType::field", "operator": "!=", "value": "No Activity" }
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Max Speed",
     "measurement": "ActivitySummary",
     "query": "SELECT \"duration\" FROM \"Activity Records\" WHERE (\"ActivityName\" = 'Walk') AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "maxSpeed" ], "type": "field" },
       { "params": [ "* 3.6" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "activityType::field", "operator": "!=", "value": "No Activity" }
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Distance",
     "measurement": "ActivitySummary",
     "query": "SELECT \"duration\" FROM \"Activity Records\" WHERE (\"ActivityName\" = 'Walk') AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "distance" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "activityType::field", "operator": "!=", "value": "No Activity" }
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Location",
     "measurement": "ActivitySummary",
     "query": "SELECT \"duration\" FROM \"Activity Records\" WHERE (\"ActivityName\" = 'Walk') AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "locationName" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "activityType::field", "operator": "!=", "value": "No Activity" }
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Activities",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "Activity Timeline",
     "measurement": "ActivitySummary",
     "select": [
      [
       { "params": [ "activityType" ], "type": "field" }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  { "title": "GPS Track Maps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "GPS Track by Velocity",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "lat",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "Latitude" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    },
    {
     "alias": "lon",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "Longitude" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    },
    {
     "alias": "HR",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "HeartRate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    },
    {
     "alias": "speed (Km/h)",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "Speed" ], "type": "field" },
       { "params": [ "* 3.6" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    }
   ]
  },
  {
   "title": "GPS Track by Heart Rate",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "alias": "lat",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "Latitude" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    },
    {
     "alias": "lon",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "Longitude" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    },
    {
     "alias": "HR",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "HeartRate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    },
    {
     "alias": "speed",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "Speed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    }
   ]
  },
  { "title": "Activity Detail Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "GPS Track Heart Rate",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "HR",
     "measurement": "ActivityGPS",
     "query": "SELECT \"HeartRate\" FROM \"ActivityGPS\" WHERE (\"ActivitySelector\"::tag =~ /^$ActivityGPS$/)",
     "select": [
      [
       { "params": [ "HeartRate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    }
   ]
  },
  {
   "title": "GPS Track Cadence",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Cadence",
     "measurement": "ActivityGPS",
     "query": "SELECT (1000/(\"Cadence\"* 60)) FROM \"ActivityGPS\" WHERE (\"ActivitySelector\"::tag =~ /^$ActivityGPS$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "Cadence" ], "type": "field" },
       { "params": [ "* 2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    }
   ]
  },
  {
   "title": "Distance vs HR",
   "type": "trend",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "alias": "Distance",
     "measurement": "ActivityGPS",
     "query": "SELECT \"HeartRate\" FROM \"ActivityGPS\" WHERE (\"ActivitySelector\"::tag =~ /^$ActivityGPS$/)",
     "select": [
      [
       { "params": [ "Distance" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    },
    {
     "alias": "Heart Rate",
     "measurement": "ActivityGPS",
     "query": "SELECT \"HeartRate\" FROM \"ActivityGPS\" WHERE (\"ActivitySelector\"::tag =~ /^$ActivityGPS$/)",
     "select": [
      [
       { "params": [ "HeartRate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    },
    {
     "alias": "Pace",
     "measurement": "ActivityGPS",
     "query": "SELECT \"HeartRate\" FROM \"ActivityGPS\" WHERE (\"ActivitySelector\"::tag =~ /^$ActivityGPS$/)",
     "select": [
      [
       { "params": [ "Speed" ], "type": "field" },
       { "params": [ "* 3.6" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    },
    {
     "alias": "Duration",
     "measurement": "ActivityGPS",
     "query": "SELECT \"HeartRate\" FROM \"ActivityGPS\" WHERE (\"ActivitySelector\"::tag =~ /^$ActivityGPS$/)",
     "select": [
      [
       { "params": [ "DurationSeconds" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    }
   ]
  },
  {
   "title": "Heart Rate vs Pace",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "alias": "Speed (Km/h)",
     "measurement": "ActivityGPS",
     "query": "SELECT \"HeartRate\" FROM \"ActivityGPS\" WHERE (\"ActivitySelector\"::tag =~ /^$ActivityGPS$/)",
     "select": [
      [
       { "params": [ "Speed" ], "type": "field" },
       { "params": [ "* 3.6" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    },
    {
     "alias": "Heart Rate",
     "measurement": "ActivityGPS",
     "query": "SELECT \"HeartRate\" FROM \"ActivityGPS\" WHERE (\"ActivitySelector\"::tag =~ /^$ActivityGPS$/)",
     "select": [
      [
       { "params": [ "HeartRate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    }
   ]
  },
  {
   "title": "GPS Track pace",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "alias": "m/s",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Speed\" FROM \"ActivityGPS\" WHERE \"Speed\" > 0 AND  (\"ActivitySelector\"::tag =~ /^$ActivityGPS$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "Speed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    },
    {
     "alias": "Duration",
     "measurement": "ActivityGPS",
     "query": "SELECT \"HeartRate\" FROM \"ActivityGPS\" WHERE (\"ActivitySelector\"::tag =~ /^$ActivityGPS$/)",
     "select": [
      [
       { "params": [ "DurationSeconds" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    }
   ]
  },
  {
   "title": "GPS Track Altitude",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Altitude",
     "measurement": "ActivityGPS",
     "query": "SELECT \"HeartRate\" FROM \"ActivityGPS\" WHERE (\"ActivitySelector\"::tag =~ /^$ActivityGPS$/)",
     "select": [
      [
       { "params": [ "Altitude" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    }
   ]
  }
 ]
}