{
 "title": "Garmin Stats",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "TimeZone",
    "label": "Local Time Zone",
    "query": "Europe/London, Europe/Paris, Europe/Berlin, Europe/Madrid, Europe/Rome, Europe/Amsterdam, Europe/Brussels, Europe/Zurich, Europe/Stockholm, Europe/Warsaw, Europe/Budapest, Europe/Istanbul, Europe/Athens, Europe/Moscow, America/New_York, America/Chicago, America/Denver, America/Los_Angeles, America/Toronto, America/Vancouver, America/Mexico_City, America/Sao_Paulo, America/Buenos_Aires, America/Lima, America/Bogota, Africa/Johannesburg, Africa/Cairo, Africa/Nairobi, Africa/Lagos, Asia/Tokyo, Asia/Seoul, Asia/Shanghai, Asia/Singapore, Asia/Kolkata, Asia/Bangkok, Asia/Dubai, Asia/Hong_Kong, Asia/Kuala_Lumpur, Asia/Jakarta, Asia/Manila, Asia/Taipei, Asia/Karachi, Asia/Colombo, Asia/Ho_Chi_Minh, Australia/Sydney, Australia/Melbourne, Australia/Brisbane, Australia/Perth, Pacific/Auckland, Pacific/Honolulu"
   }
  ]
 },
 "panels": [
  { "title": "Intraday Health Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Heart Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 1 },
   "targets": [
    {
     "alias": "Heart Rate",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HeartRateIntraday",
     "select": [
      [
       { "params": [ "HeartRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Sync ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "HeartRateIntraday",
     "select": [
      [
       { "params": [ "HeartRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heart Rate Distribution",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Heart rate histogram",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HeartRate_Intraday",
     "query": "select mean_value from (SELECT mean(\"HeartRate\") as mean_value FROM \"HeartRateIntraday\" WHERE $timeFilter GROUP BY time(1m) fill(null)) where mean_value <= 96",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Heart rate histogram > 96",
     "measurement": "HeartRate_Intraday",
     "query": "select mean_value from (SELECT mean(\"HeartRate\") as mean_value FROM \"HeartRateIntraday\" WHERE $timeFilter GROUP BY time(1m) fill(null)) where mean_value > 96",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Heart rate histogram < 60",
     "measurement": "HeartRate_Intraday",
     "query": "select mean_value from (SELECT mean(\"HeartRate\") as mean_value FROM \"HeartRateIntraday\" WHERE $timeFilter GROUP BY time(1m) fill(null)) where mean_value < 60",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Heart rate histogram > 110",
     "measurement": "HeartRate_Intraday",
     "query": "select mean_value from (SELECT mean(\"HeartRate\") as mean_value FROM \"HeartRateIntraday\" WHERE $timeFilter GROUP BY time(1m) fill(null)) where mean_value > 110",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 10 },
   "targets": [
    {
     "alias": "Stress",
     "measurement": "StressIntraday",
     "select": [
      [
       { "params": [ "stressLevel" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Body Battery",
     "measurement": "BodyBatteryIntraday",
     "select": [
      [
       { "params": [ "BodyBatteryLevel" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today RHR",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "restingHeartRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Today's Steps",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "totalSteps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Steps Cumulative (24h)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Intraday Steps",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StepsIntraday",
     "query": "SELECT moving_average(mean(\"value\"), 6) FROM \"HeartRate_Intraday\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "StepsCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today SpO2",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "averageSpo2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Steps Hourly (24h)",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Hourly Steps",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "StepsIntraday",
     "query": "SELECT moving_average(mean(\"value\"), 6) FROM \"HeartRate_Intraday\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "StepsCount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Last Sleep Hours",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Total Asleep",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "select": [
      [
       { "params": [ "sleepTimeSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Breathing Rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 29 },
   "targets": [
    {
     "alias": "BR",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BreathingRateIntraday",
     "select": [
      [
       { "params": [ "BreathingRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "High Stress Duration",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Stress",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "highStressDuration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Sleep Movement Activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 36 },
   "targets": [
    {
     "alias": "Sleeping Movement Activity",
     "measurement": "SleepIntraday",
     "select": [
      [
       { "params": [ "SleepMovementActivityLevel" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Sleep",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Deep",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "deepSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Light",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lightSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "REM",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "remSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Awake",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "awakeSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Sleep Intraday Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 43 },
   "targets": [
    {
     "alias": "Sleeping Heart Rate",
     "measurement": "SleepIntraday",
     "select": [
      [
       { "params": [ "heartRate" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "SpO2",
     "measurement": "SleepIntraday",
     "select": [
      [
       { "params": [ "spo2Reading" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "HRV",
     "measurement": "HRV_Intraday",
     "select": [
      [
       { "params": [ "hrvValue" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today Activity",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Sedentary",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "sedentarySeconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Intense Activity",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "vigorousIntensityMinutes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 60" ], "type": "math" }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Moderate Activity",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "moderateIntensityMinutes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 60" ], "type": "math" }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Sleeping",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "sleepingSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Sleep Stages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 52 },
   "targets": [
    {
     "alias": "Deep",
     "measurement": "SleepIntraday",
     "query": "SELECT \"SleepStageLevel\"+1 FROM \"SleepIntraday\" WHERE SleepStageLevel=0 AND $timeFilter",
     "select": [
      [
       { "params": [ "SleepStageLevel" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Light",
     "measurement": "SleepIntraday",
     "query": "SELECT \"SleepStageLevel\"+1 FROM \"SleepIntraday\" WHERE SleepStageLevel=1 AND $timeFilter",
     "select": [
      [
       { "params": [ "SleepStageLevel" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "REM",
     "measurement": "SleepIntraday",
     "query": "SELECT \"SleepStageLevel\"+1 FROM \"SleepIntraday\" WHERE SleepStageLevel=2 AND $timeFilter",
     "select": [
      [
       { "params": [ "SleepStageLevel" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Awake",
     "measurement": "SleepIntraday",
     "query": "SELECT \"SleepStageLevel\"+1 FROM \"SleepIntraday\" WHERE SleepStageLevel=3 AND $timeFilter",
     "select": [
      [
       { "params": [ "SleepStageLevel" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Activity HR Zones (mean)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Zone 1",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ActivitySummary",
     "select": [
      [
       { "params": [ "hrTimeInZone_1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Zone 2",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ActivitySummary",
     "select": [
      [
       { "params": [ "hrTimeInZone_2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Zone 3",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ActivitySummary",
     "select": [
      [
       { "params": [ "hrTimeInZone_3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Zone 4",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ActivitySummary",
     "select": [
      [
       { "params": [ "hrTimeInZone_4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Zone 5",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ActivitySummary",
     "select": [
      [
       { "params": [ "hrTimeInZone_5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Activity Calories (mean)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "calories",
     "measurement": "ActivitySummary",
     "select": [
      [
       { "params": [ "calories" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "BMR calories",
     "measurement": "ActivitySummary",
     "select": [
      [
       { "params": [ "bmrCalories" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Activity HR difference (Max-Avg)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 4, "x": 10, "y": 59 },
   "targets": [
    {
     "alias": "avgHR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ActivitySummary",
     "select": [
      [
       { "params": [ "averageHR" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "maxHR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ActivitySummary",
     "select": [
      [
       { "params": [ "maxHR" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Activity Distance",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "alias": "Distance",
     "measurement": "ActivitySummary",
     "select": [
      [
       { "params": [ "distance" ], "type": "field" }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Activity Duration",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Duration",
     "measurement": "ActivitySummary",
     "select": [
      [
       { "params": [ "elapsedDuration" ], "type": "field" }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  { "title": "Long term visualization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Week at a Glance",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "alias": "Distance Covered",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "totalDistanceMeters" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Steps",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "totalSteps" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Total Sleep",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "sleepingSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "High Stress Duration",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "highStressDuration" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "High Activity Duration",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "highlyActiveSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Resting Heart Rate",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "restingHeartRate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Avg SpO2",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "averageSpo2" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Body Battery Change",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "bodyBatteryChargedValue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Daily Steps",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Steps",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "totalSteps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Daily Distance",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "alias": "Distance Covered",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "totalDistanceMeters" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Daily Calories",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "BMR Calories",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "bmrKilocalories" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Activity Calories",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "activeKilocalories" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Daily avg health metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Avg SpO2",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "select": [
      [
       { "params": [ "averageSpO2Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Avg HRV",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HRV_Intraday",
     "select": [
      [
       { "params": [ "hrvValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Avg Resting HR",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "restingHeartRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Daily avg health metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Avg Breathing Rate",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BreathingRateIntraday",
     "select": [
      [
       { "params": [ "BreathingRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Avg Stress",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StressIntraday",
     "select": [
      [
       { "params": [ "stressLevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Avg Sleeping Stress",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "select": [
      [
       { "params": [ "avgSleepStress" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Race Predictions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "alias": "Time 5K",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RacePredictions",
     "select": [
      [
       { "params": [ "time5K" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Time 10K",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RacePredictions",
     "select": [
      [
       { "params": [ "time10K" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Half Marathon",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RacePredictions",
     "select": [
      [
       { "params": [ "timeHalfMarathon" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Full Marathon",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RacePredictions",
     "select": [
      [
       { "params": [ "timeMarathon" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "VO2 Max",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "VO2 Max",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "VO2_Max",
     "select": [
      [
       { "params": [ "VO2_max_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Heatmap for GPS Activity (within selected time)",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 98 },
   "targets": [
    {
     "alias": "lat",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "Latitude" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "lon",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "Longitude" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sleep Stages",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "alias": "Deep Sleep",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "select": [
      [
       { "params": [ "deepSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Light Sleep",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "select": [
      [
       { "params": [ "lightSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "REM Sleep",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "select": [
      [
       { "params": [ "remSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Awake",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "select": [
      [
       { "params": [ "awakeSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Avg Activity over given duration",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 9, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Sedentary",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "sedentarySeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Intense Activity",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "highlyActiveSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Fair Activity",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "activeSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Sleeping",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "sleepingSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Sleep Score",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Sleep Score",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "select": [
      [
       { "params": [ "sleepScore" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Daily Activity Overview",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "alias": "Sleeping",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "sleepingSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Sedentary",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "sedentarySeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Active",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "activeSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Highly Active",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "highlyActiveSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Body Battery overview",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Charged",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "bodyBatteryChargedValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Drained",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "bodyBatteryDrainedValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1" ], "type": "math" }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Daily Intensity Minutes",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "alias": "Moderate Intensity",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "moderateIntensityMinutes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* 60" ], "type": "math" }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Vigorous Intensity",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "vigorousIntensityMinutes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* 60" ], "type": "math" }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Stress overview",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "alias": "Low Stress duration",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "lowStressDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Rest stress duration",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "restStressDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Medium stress duration",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "mediumStressDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Uncategorized stress duration",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "uncategorizedStressDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "High stress duration",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "highStressDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Average Sleep trends",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Deep",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "deepSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Light",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lightSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "REM",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "remSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Awake",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "awakeSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Body Battery Level Change",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 130 },
   "targets": [
    {
     "alias": "bb_low",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "bodyBatteryLowestValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "bb_high",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "bodyBatteryHighestValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Weight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    {
     "alias": "Weight in KG",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BodyComposition",
     "select": [
      [
       { "params": [ "weight" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "HR Range (Max-Min)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 137 },
   "targets": [
    {
     "alias": "hr_low",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "minHeartRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "hr_high",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "maxHeartRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Month at a Glance (Daily Average)",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 144 },
   "targets": [
    {
     "alias": "Resting HR",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "restingHeartRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "High Stress Duration",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "highStressDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Active time",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "activeSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Body Battery (Highest)",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "bodyBatteryHighestValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Total Steps",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "totalSteps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "SpO2",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "averageSpo2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Sleep Score",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "select": [
      [
       { "params": [ "sleepScore" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Total Sleep",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "sleepingSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "HRV",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HRV_Intraday",
     "select": [
      [
       { "params": [ "hrvValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Month at a Glance (Intraday)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 155 },
   "targets": [
    {
     "alias": "Band Wearing",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "HeartRateIntraday",
     "select": [
      [
       { "params": [ "HeartRate" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "HR Zones",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HeartRateIntraday",
     "select": [
      [
       { "params": [ "HeartRate" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    },
    {
     "alias": "Body Battery",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BodyBatteryIntraday",
     "select": [
      [
       { "params": [ "BodyBatteryLevel" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    },
    {
     "alias": "Stress Level",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StressIntraday",
     "select": [
      [
       { "params": [ "stressLevel" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    },
    {
     "alias": "Steps Taken",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StepsIntraday",
     "select": [
      [
       { "params": [ "StepsCount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HR Histogram Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 163 },
   "targets": [
    {
     "alias": "Heart Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HeartRateIntraday",
     "select": [
      [
       { "params": [ "HeartRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hourly walk heatmap",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Hourly Steps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StepsIntraday",
     "select": [
      [
       { "params": [ "StepsCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Sleep Regularity",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 171 },
   "targets": [
    {
     "alias": "Sleep Regularity",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "SleepIntraday",
     "query": "SELECT median(\"level\") FROM \"Sleep Levels\" WHERE $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "SleepStageLevel" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Battery Level (Requires GarminHomeAssistant from ConnectIQ integration)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 181 },
   "targets": [
    {
     "alias": "Device Battery Level",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}